# Generated by Django 5.0.1 on 2024-04-14 14:27

from django.db import migrations

import random
from faker import Faker
from django.utils import timezone
from users.models import Department, Worker

fake = Faker()

def populate_users(apps, schema_editor):
    # Define department names
    departments = ['IT', 'Marketing', 'Finance', 'Human Resources', 'Operations']

    # Define sectors
    sectors = ['A', 'B', 'C', 'D', 'E']

    # Populate Department table
    for dept_name in departments:
        Department.objects.create(name=dept_name)

    # Populate Worker table
    for _ in range(50):
        name = fake.name()
        department = random.choice(Department.objects.all())
        salary = random.randint(30000, 100000)
        sector = random.choice(sectors)
        Worker.objects.create(name=name, department=department, salary=salary, sector=sector)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_department_table_alter_worker_table'),
    ]

    operations = [
        migrations.RunPython()
    ]
