version: '3.1'

services:
  postgres:
    image: postgres:13.4
    shm_size: 1g
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
    - pg_data:/var/lib/postgresql/data

    logging:
      driver: none

volumes:
  pg_data:
